# Generated by Django 6.0.4 on 2026-04-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên/Mã thiết bị')),
                ('device_type', models.CharField(choices=[('ELECTRIC_POLE', 'Trụ Điện'), ('WATER_METER', 'Đồng Hồ Nước'), ('TRANSFORMER', 'Trạm Biến Áp'), ('VALVE', 'Van Nước')], max_length=20, verbose_name='Loại hạ tầng')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ (Latitude)')),
                ('longitude', models.FloatField(verbose_name='Kinh độ (Longitude)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thiết bị hạ tầng',
                'verbose_name_plural': 'Danh sách Thiết bị',
            },
        ),
    ]
