# Generated by Django 4.2.27 on 2026-04-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày ghi nhận')),
                ('value', models.FloatField(verbose_name='Chỉ số tiêu thụ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='assets.device', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'Nhật ký tiêu thụ',
                'verbose_name_plural': 'Nhật ký tiêu thụ',
                'unique_together': {('device', 'date')},
            },
        ),
    ]
