# Generated by Django 4.2.27 on 2026-04-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_consumptionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Thuộc tính mở rộng'),
        ),
        migrations.AddField(
            model_name='device',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.device', verbose_name='Thiết bị cấp nguồn'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('ELECTRIC_POLE', 'Trụ Điện'), ('ELECTRIC_METER', 'Công tơ điện'), ('WATER_METER', 'Đồng Hồ Nước'), ('TRANSFORMER', 'Trạm Biến Áp'), ('VALVE', 'Van Nước')], max_length=20, verbose_name='Loại hạ tầng'),
        ),
    ]
