# Generated by Django 4.2.27 on 2026-05-16 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0001_initial'),
        ('assets', '0003_device_attributes_device_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Mã tuyến')),
                ('name', models.CharField(max_length=150, verbose_name='Tên tuyến')),
                ('network_type', models.CharField(choices=[('ELECTRIC', 'Điện'), ('WATER', 'Nước')], max_length=10, verbose_name='Loại mạng')),
                ('status', models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('FAULT', 'Lỗi trực tiếp'), ('AFFECTED', 'Bị ảnh hưởng'), ('MAINTENANCE', 'Đang bảo trì'), ('INACTIVE', 'Ngưng sử dụng')], default='ACTIVE', max_length=16, verbose_name='Trạng thái')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tuyến mạng lưới',
                'verbose_name_plural': 'Tuyến mạng lưới',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='device',
            name='area',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Khu vực'),
        ),
        migrations.AddField(
            model_name='device',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Mã thiết bị'),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('FAULT', 'Lỗi trực tiếp'), ('AFFECTED', 'Bị ảnh hưởng'), ('MAINTENANCE', 'Đang bảo trì'), ('INACTIVE', 'Ngưng hoạt động')], default='ACTIVE', max_length=16, verbose_name='Trạng thái mạng'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('TRANSFORMER', 'Trạm biến áp'), ('DISTRIBUTION_BOX', 'Tủ điện / tủ phân phối'), ('ELECTRIC_POLE', 'Trụ điện'), ('ELECTRIC_JUNCTION', 'Điểm nối điện'), ('ELECTRIC_METER', 'Công tơ điện'), ('WATER_TANK', 'Bể chứa nước'), ('PUMP_STATION', 'Trạm bơm'), ('MAIN_VALVE', 'Van tổng'), ('BRANCH_VALVE', 'Van nhánh'), ('WATER_JUNCTION', 'Điểm nối nước'), ('WATER_METER', 'Đồng hồ nước'), ('VALVE', 'Van nước (cũ)')], max_length=32, verbose_name='Loại hạ tầng'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Trạng thái hoạt động (legacy)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Tên thiết bị'),
        ),
        migrations.AlterField(
            model_name='device',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.device', verbose_name='Thiết bị cấp nguồn (legacy)'),
        ),
        migrations.CreateModel(
            name='NetworkStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('DEVICE', 'Thiết bị'), ('EDGE', 'Tuyến')], max_length=10)),
                ('old_status', models.CharField(max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.device')),
                ('edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.networkedge')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Lịch sử trạng thái mạng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='networkedge',
            name='from_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='assets.device', verbose_name='Thiết bị đầu'),
        ),
        migrations.AddField(
            model_name='networkedge',
            name='to_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='assets.device', verbose_name='Thiết bị cuối'),
        ),
        migrations.AddConstraint(
            model_name='networkedge',
            constraint=models.UniqueConstraint(fields=('from_device', 'to_device'), name='unique_edge_direction'),
        ),
    ]
