# Generated by Django 4.2.27 on 2026-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_graph_network_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkedge',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Thuộc tính mở rộng'),
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.CharField(default='DEV_DEFAULT', max_length=64, unique=True, verbose_name='Mã thiết bị'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('TRANSFORMER', 'Trạm biến áp'), ('DISTRIBUTION_BOX', 'Tủ điện / tủ phân phối'), ('ELECTRIC_POLE', 'Trụ điện'), ('ELECTRIC_JUNCTION', 'Điểm nối điện'), ('ELECTRIC_METER', 'Công tơ điện'), ('WATER_TANK', 'Bể nước'), ('PUMP_STATION', 'Trạm bơm'), ('MAIN_VALVE', 'Van tổng'), ('BRANCH_VALVE', 'Van nhánh'), ('WATER_JUNCTION', 'Điểm nối nước'), ('WATER_METER', 'Đồng hồ nước'), ('VALVE', 'Van nước (cũ)')], max_length=32, verbose_name='Loại hạ tầng'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('FAULT', 'Lỗi trực tiếp'), ('MAINTENANCE', 'Đang bảo trì'), ('INACTIVE', 'Ngưng hoạt động')], default='ACTIVE', max_length=16, verbose_name='Trạng thái mạng'),
        ),
        migrations.AlterField(
            model_name='networkedge',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('FAULT', 'Lỗi trực tiếp'), ('MAINTENANCE', 'Đang bảo trì'), ('INACTIVE', 'Ngưng sử dụng')], default='ACTIVE', max_length=16, verbose_name='Trạng thái'),
        ),
    ]
