# Generated by Django 5.2.14 on 2026-05-30 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_networkedge_attributes_alter_device_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã phường/xã')),
                ('name', models.CharField(max_length=120, verbose_name='Tên đầy đủ')),
                ('short_name', models.CharField(max_length=80, verbose_name='Tên ngắn')),
                ('district', models.CharField(max_length=80, verbose_name='Quận/Huyện')),
                ('unit_type', models.CharField(choices=[('PHUONG', 'Phường'), ('XA', 'Xã')], default='PHUONG', max_length=10, verbose_name='Loại đơn vị')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ (tâm)')),
                ('longitude', models.FloatField(verbose_name='Kinh độ (tâm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
            ],
            options={
                'verbose_name': 'Phường/Xã',
                'verbose_name_plural': 'Đơn vị hành chính Đà Nẵng',
                'ordering': ['district', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='area',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Khu vực (đồng bộ)'),
        ),
        migrations.AddField(
            model_name='device',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='assets.ward', verbose_name='Phường/Xã'),
        ),
    ]
