# Generated by Django 5.2.14 on 2026-05-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_failed_login_attempts_auditlog'),
        ('assets', '0006_ward_alter_device_area_device_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_wards',
            field=models.ManyToManyField(blank=True, help_text='OPERATOR/TECHNICIAN chỉ thao tác dữ liệu trong các phường/xã này. ADMIN bỏ trống = toàn thành phố.', related_name='staff_users', to='assets.ward', verbose_name='Phường/Xã được phân quyền'),
        ),
    ]
