# Generated by Django 4.2.27 on 2026-04-27 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0003_device_attributes_device_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề sự cố')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('incident_type', models.CharField(choices=[('ELECTRIC', 'Điện'), ('WATER', 'Nước'), ('OTHER', 'Khác')], default='OTHER', max_length=10, verbose_name='Loại sự cố')),
                ('severity', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('CRITICAL', 'Khẩn cấp')], default='MEDIUM', max_length=10, verbose_name='Mức độ nghiêm trọng')),
                ('status', models.CharField(choices=[('OPEN', 'Mới'), ('ASSIGNED', 'Đã phân công'), ('IN_PROGRESS', 'Đang xử lý'), ('RESOLVED', 'Đã xử lý'), ('CLOSED', 'Đóng')], default='OPEN', max_length=15, verbose_name='Trạng thái')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian giải quyết')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Kỹ thuật viên phụ trách')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='assets.device', verbose_name='Thiết bị liên quan')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Người báo cáo')),
            ],
            options={
                'verbose_name': 'Sự cố',
                'verbose_name_plural': 'Danh sách Sự cố',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('NEW_INCIDENT', 'Sự cố mới'), ('ASSIGNED', 'Được phân công'), ('STATUS_UPDATE', 'Cập nhật trạng thái'), ('RESOLVED', 'Đã giải quyết')], max_length=20, verbose_name='Loại thông báo')),
                ('message', models.CharField(max_length=500, verbose_name='Nội dung')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='incidents.incident', verbose_name='Sự cố liên quan')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người ghi')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='incidents.incident', verbose_name='Sự cố')),
            ],
            options={
                'verbose_name': 'Ghi chú sự cố',
                'ordering': ['created_at'],
            },
        ),
    ]
