# Generated by Django 4.2.27 on 2026-05-16 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0004_graph_network_upgrade'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='incident',
            name='area',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Khu vực'),
        ),
        migrations.AddField(
            model_name='incident',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận'),
        ),
        migrations.AddField(
            model_name='incident',
            name='edge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='assets.networkedge', verbose_name='Tuyến liên quan'),
        ),
        migrations.AddField(
            model_name='incident',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='Lý do từ chối'),
        ),
        migrations.AddField(
            model_name='incident',
            name='result_note',
            field=models.TextField(blank=True, default='', verbose_name='Kết quả xử lý'),
        ),
        migrations.AddField(
            model_name='incident',
            name='target_type',
            field=models.CharField(choices=[('DEVICE', 'Thiết bị'), ('EDGE', 'Tuyến'), ('UNKNOWN', 'Chưa xác định')], default='UNKNOWN', max_length=10, verbose_name='Loại đích'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFY', 'Chờ xác minh'), ('CONFIRMED', 'Đã xác nhận'), ('ASSIGNED', 'Đã phân công'), ('IN_PROGRESS', 'Đang xử lý'), ('RESOLVED', 'Đã xử lý'), ('CLOSED', 'Đã đóng'), ('REJECTED', 'Từ chối')], default='PENDING_VERIFY', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('NEW_INCIDENT', 'Sự cố mới'), ('ASSIGNED', 'Được phân công'), ('STATUS_UPDATE', 'Cập nhật trạng thái'), ('RESOLVED', 'Đã giải quyết'), ('CONFIRMED', 'Đã xác nhận'), ('REJECTED', 'Từ chối')], max_length=20, verbose_name='Loại thông báo'),
        ),
        migrations.CreateModel(
            name='IncidentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Lịch sử sự cố',
                'ordering': ['-created_at'],
            },
        ),
    ]
