# Generated by Django 5.2.14 on 2026-05-30 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_ward_alter_device_area_device_ward'),
        ('incidents', '0003_migrate_legacy_incidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='assets.ward', verbose_name='Phường/Xã'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='area',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Khu vực (đồng bộ)'),
        ),
    ]
